# Generated by Django 5.0.6 on 2024-09-25 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('birthday', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cellphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)])),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellphones', to='app_foto.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app_foto.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('Chá revelação', 'Cha Revelacao'), ('Chá de bebê', 'Cha Bebe'), ('Acompanhamento 12 meses', 'Acompanhamento 12 Meses'), ('Aniversário 1 ano', 'Aniversario 1 Ano'), ('Aniversário outros', 'Aniversario Outros'), ('Festa de debutante', 'Festa Debutante'), ('Pré-Wedding', 'Pre Wedding'), ('Casamento', 'Casamento'), ('Outros', 'Outros')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_foto.client')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_foto.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
