# Generated by Django 5.1.2 on 2024-10-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=15)),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
                ("estado", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("cha_revelacao", "Chá Revelação"),
                            ("cha_bebe", "Chá de Bebê"),
                            ("acompanhamento_12_meses", "Acompanhamento 12 meses"),
                            ("aniversario_1_ano", "Aniversário 1 ano"),
                            ("aniversario_outros", "Aniversário outros"),
                            ("festa_debutante", "Festa de debutante"),
                            ("formatura", "Formatura"),
                            ("pre_wedding", "Pré-Wedding"),
                            ("casamento", "Casamento"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrcamentoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("cha_revelacao", "Chá Revelação"),
                            ("cha_bebe", "Chá de Bebê"),
                            ("acompanhamento_12_meses", "Acompanhamento 12 meses"),
                            ("aniversario_1_ano", "Aniversário 1 ano"),
                            ("aniversario_outros", "Aniversário outros"),
                            ("festa_debutante", "Festa de debutante"),
                            ("formatura", "Formatura"),
                            ("pre_wedding", "Pré-Wedding"),
                            ("casamento", "Casamento"),
                            ("outros", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_evento", models.DateField()),
                ("local_evento", models.CharField(max_length=100)),
                (
                    "descricao",
                    models.CharField(default="descrição padrão", max_length=255),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Chá revelação", "Cha Revelacao"),
                            ("Chá de bebê", "Cha Bebe"),
                            ("Acompanhamento 12 meses", "Acompanhamento 12 Meses"),
                            ("Aniversário 1 ano", "Aniversario 1 Ano"),
                            ("Aniversário outros", "Aniversario Outros"),
                            ("Festa de debutante", "Festa Debutante"),
                            ("Formatura", "Formatura"),
                            ("Pré-Wedding", "Pre Wedding"),
                            ("Casamento", "Casamento"),
                            ("Outros", "Outros"),
                        ],
                        default="Outros",
                        max_length=50,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoImpressao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho_foto",
                    models.CharField(
                        choices=[
                            ("10x15", "10x15 cm"),
                            ("15x21", "15x21 cm"),
                            ("20x30", "20x30 cm"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
    ]
