# Generated by Django 5.0.6 on 2024-09-25 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellphone',
            name='area_code',
            field=models.IntegerField(help_text='Informe o código de área com dois dígitos (ex: 11 para São Paulo)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cellphone',
            name='number',
            field=models.IntegerField(help_text='Informe o número de telefone sem o código de área', validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
