# Generated by Django 5.0.6 on 2024-10-19 03:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0002_remove_cliente_bairro_remove_cliente_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='acabamento_especial',
            field=models.BooleanField(default=False, verbose_name='Acabamento do álbum especial?'),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='acabamento_simples',
            field=models.BooleanField(default=False, verbose_name='Acabamento do álbum simples?'),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='apenas_digital',
            field=models.BooleanField(default=False, verbose_name='Apenas digital?'),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='apenas_foto',
            field=models.BooleanField(default=False, verbose_name='Apenas foto?'),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='foto_video',
            field=models.BooleanField(default=False, verbose_name='Foto e vídeo?'),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='outros_detalhes',
            field=models.CharField(default=datetime.datetime(2024, 10, 19, 3, 35, 3, 408524, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='registros_impressos',
            field=models.BooleanField(default=False, verbose_name='Registros impressos?'),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_foto.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='local_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_foto.endereco'),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='tipo_evento',
            field=models.CharField(choices=[('cha_revelacao', 'Chá Revelação'), ('cha_bebe', 'Chá de Bebê'), ('acompanhamento_12_meses', 'Acompanhamento 12 meses'), ('aniversario_1_ano', 'Aniversário 1 ano'), ('aniversario_outros', 'Aniversário outros'), ('festa_debutante', 'Festa de debutante'), ('formatura', 'Formatura'), ('pre_wedding', 'Pré-Wedding'), ('casamento', 'Casamento'), ('corporativo', 'Evento corporativo'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoimpressao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_foto.cliente'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
