# Generated by Django 5.0.6 on 2024-10-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0003_remove_pedido_cliente_delete_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoevento',
            name='outros_detalhes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
