# Generated by Django 5.0.6 on 2024-10-21 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0004_alter_orcamentoevento_outros_detalhes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Nome do recurso adicional', max_length=100, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço para este recurso', max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço para este tipo de evento', max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='acabamento_especial',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='acabamento_simples',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='apenas_digital',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='apenas_foto',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='foto_video',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='registros_impressos',
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedidoimpressao',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedidoimpressao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='recursos_adicionais',
            field=models.ManyToManyField(blank=True, related_name='orcamentos', to='app_foto.recursoevento'),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='app_foto.tipoevento'),
        ),
    ]
