# Generated by Django 5.0.6 on 2024-10-21 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0006_tamanhofoto_remove_pedidoimpressao_preco_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoimpressao',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedidoimpressao',
            name='tamanho_foto',
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_foto.pedidoimpressao')),
                ('tamanho_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_foto.tamanhofoto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
