# Generated by Django 5.0.6 on 2024-10-24 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0007_remove_pedidoimpressao_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoevento',
            name='hora_evento',
            field=models.TimeField(default=datetime.datetime(2024, 10, 24, 2, 35, 37, 773235, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
