# Generated by Django 5.0.6 on 2024-10-27 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0008_orcamentoevento_hora_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='codigo_area',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
