# Generated by Django 5.0.6 on 2024-10-27 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0010_remove_cliente_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='rua',
            new_name='logradouro',
        ),
        migrations.AlterField(
            model_name='telefone',
            name='codigo_area',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
