# Generated by Django 5.0.6 on 2024-10-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0011_rename_rua_endereco_logradouro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoevento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recursoevento',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
