# Generated by Django 5.0.6 on 2024-10-31 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0013_remove_orcamentoevento_local_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='local_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_evento', to='app_foto.orcamentoevento'),
        ),
    ]
