# Generated by Django 5.0.6 on 2024-10-31 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0014_alter_endereco_local_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='local_evento',
        ),
        migrations.AddField(
            model_name='endereco',
            name='orcamento_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_foto.orcamentoevento'),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='local_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_evento', to='app_foto.endereco'),
        ),
    ]
