# Generated by Django 5.0.6 on 2024-10-31 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0015_remove_endereco_local_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='orcamento_evento',
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='bairro',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 50, 22, 794605, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='cep',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 50, 35, 666669, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='cidade',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 50, 52, 588768, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='estado',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 51, 8, 40746, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='logradouro',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 51, 35, 468669, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='numero',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 51, 43, 495629, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='local_evento',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 51, 50, 123112, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
