# Generated by Django 5.0.6 on 2024-10-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0016_remove_endereco_orcamento_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
