# Generated by Django 5.0.6 on 2024-10-31 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0017_alter_endereco_cep_alter_orcamentoevento_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='orcamentoevento',
            name='numero',
        ),
        migrations.AddField(
            model_name='endereco',
            name='orcamento_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_foto.orcamentoevento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='local_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_evento', to='app_foto.endereco'),
        ),
    ]
