# Generated by Django 5.0.6 on 2024-11-01 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foto', '0018_remove_orcamentoevento_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='orcamento_evento',
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='bairro',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 0, 59, 44, 484118, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='cep',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 0, 59, 49, 935235, tzinfo=datetime.timezone.utc), max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='cidade',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 0, 59, 54, 855504, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='estado',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 0, 59, 57, 737714, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='logradouro',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 1, 0, 1, 91504, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoevento',
            name='numero',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 1, 0, 3, 651674, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='orcamentoevento',
            name='local_evento',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 1, 0, 6, 793534, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
